; Script generated by the SmartDine DevOps pipeline.
; Installs PostgreSQL 16 silently, configures local JRE, registers and runs Spring Boot as a service.

[Setup]
AppId={{C6B5E87D-89EA-4E52-9A4B-914856E3B8F1}
AppName=Surabhi SmartDine
AppVersion=1.0.0
AppPublisher=Surabhi Technologies
DefaultDirName={commonpf}\SurabhiSmartDine
DefaultGroupName=Surabhi SmartDine
OutputDir=Output
OutputBaseFilename=smartdine-setup
Compression=lzma
SolidCompression=yes
SetupIconFile=favicon.ico
DisableProgramGroupPage=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
; PostgreSQL 16 offline installer (Assumed placed in the deployment files root)
Source: "postgresql-16-windows-x64.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall

; Application binaries and configs
Source: "smartdine-heart.jar"; DestDir: "{app}"; Flags: ignoreversion
Source: "smartdine-service.exe"; DestDir: "{app}"; DestName: "smartdine-service.exe"; Flags: ignoreversion
Source: "smartdine-service.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "favicon.ico"; DestDir: "{app}"; Flags: ignoreversion

; Bundled Java 21 Runtime Environment
Source: "jre\*"; DestDir: "{app}\jre"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{commondesktop}\Surabhi SmartDine"; Filename: "{app}\jre\bin\javaw.exe"; Parameters: "-jar ""{app}\smartdine-heart.jar"""; IconFilename: "{app}\favicon.ico"

[Run]
; 1. Install PostgreSQL 16 silently
Filename: "{tmp}\postgresql-16-windows-x64.exe"; Parameters: "--mode unattended --unattendedmodeui none --postgrespassword admin123 --port 5432"; StatusMsg: "Installing PostgreSQL 16 Database Server (please wait)..."; Flags: runhidden waituntilterminated

; 2. Register SmartDine background service wrapper
Filename: "{app}\smartdine-service.exe"; Parameters: "install"; StatusMsg: "Configuring SmartDine background service..."; Flags: runhidden waituntilterminated

; 3. Start SmartDine background service
Filename: "{app}\smartdine-service.exe"; Parameters: "start"; StatusMsg: "Starting SmartDine service..."; Flags: runhidden waituntilterminated

[UninstallRun]
; Stop and remove the Windows service wrapper during uninstallation
Filename: "{app}\smartdine-service.exe"; Parameters: "stop"; Flags: runhidden waituntilterminated
Filename: "{app}\smartdine-service.exe"; Parameters: "uninstall"; Flags: runhidden waituntilterminated
